version: '3.8'

services:
  jwt-service:
    build:
      context: .
      dockerfile: Dockerfile
    image: jwt-service:1.0.0
    container_name: jwt-service
    ports:
      - "8080:8080"
    environment:
      - SERVER_PORT=8080
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:h2:file:/data/jwtservice
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.h2.Driver
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.H2Dialect
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - JWT_SERVICE_KEY=LvDU24MmZXWkNHhtqCVwixgJ1VcmzdheLTvPDBxPMN0=
      - JWT_TOKEN_EXPIRATION=3600000
      - LOGGING_LEVEL_ORG_SPRINGFRAMEWORK=INFO
      - LOGGING_LEVEL_COM_MSINYU_JWTSERVICE=DEBUG
    volumes:
      - ./logs:/app/logs
      - h2-data:/data

volumes:
  h2-data: